execute pathogen#infect()
syntax on
filetype plugin indent on

set number

" https://realpython.com/blog/python/vim-and-python-a-match-made-in-heaven/
" split navigations
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" folding
set foldmethod=indent
set foldlevel=99

nnoremap <space> za

" default to 2 spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set textwidth=256
set expandtab
set autoindent
set fileformat=unix

set encoding=utf-8

" PEP8
au BufNewFile,BufRead *.py
      \set tabstop=4
      \set softtabstop=4
      \set shiftwidth=4
      \set textwidth=79

" NERDTree
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P
set statusline+=%{fugitive#statusline()}
